// Copyright Epic Games, Inc. All Rights Reserved.

#include "AINPC.h"
#include "Modules/ModuleManager.h"

IMPLEMENT_PRIMARY_GAME_MODULE( FDefaultGameModuleImpl, AINPC, "AINPC" );

DEFINE_LOG_CATEGORY(LogAINPC)
DEFINE_LOG_CATEGORY(LogAINPCBrain);
DEFINE_LOG_CATEGORY(LogAINPCMemory);
DEFINE_LOG_CATEGORY(LogAINPCSocial);
DEFINE_LOG_CATEGORY(LogAINPCUtility);
DEFINE_LOG_CATEGORY(LogAINPCNarrative);
DEFINE_LOG_CATEGORY(LogAINPCTargetSelection);
DEFINE_LOG_CATEGORY(LogAINPCLLM);
DEFINE_LOG_CATEGORY(LogAINPCDirector);
DEFINE_LOG_CATEGORY(LogAINPCVillage);
DEFINE_LOG_CATEGORY(LogAINPCBuilding);
DEFINE_LOG_CATEGORY(LogAINPCCombatStateTree);
DEFINE_LOG_CATEGORY(LogAINPCFactionReputation);
DEFINE_LOG_CATEGORY(LogAINPCCombat);
