// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Interfaces/IHttpRequest.h"
#include "UObject/NoExportTypes.h"
#include "UtilityAI/MentalStateFields.h"  // ✅ 引入字段配置
#include "LLMCommunicator.generated.h"

class USentimentMapper;

// 1. The Data Structure (自动生成)
USTRUCT(BlueprintType)
struct FMentalState
{
	GENERATED_BODY()
	
	// ✅ 使用宏自动生成所有字段
	#define DECLARE_MENTAL_STATE_FIELD(Name, DefaultValue, DisplayName, Description) \
		UPROPERTY() float Name = DefaultValue;
	
	MENTAL_STATE_FIELDS(DECLARE_MENTAL_STATE_FIELD)
	
	#undef DECLARE_MENTAL_STATE_FIELD
	
	// 情绪标签 / Emotion Label
	// LLM 返回的情绪描述，用于显示 emoji 和对话泡泡
	// Emotion description returned by LLM, used for emoji and speech bubble display
	// Examples: "Happy", "Angry", "Scared", "Confused", "Excited"
	UPROPERTY(BlueprintReadWrite)
	FString Emotion = TEXT("Neutral");
	
	// 对话内容 / Speech Content
	// LLM 根据当前情景生成的短对话
	// Short dialogue generated by LLM based on current situation
	// Example: "A human! I must attack!", "Who are you?", "Stay away from me!"
	UPROPERTY(BlueprintReadWrite)
	FString Speech = TEXT("");
};

// 2. The Callback Delegate
DECLARE_DELEGATE_TwoParams(FOnLLMResponse, bool /*bSuccess*/, const FMentalState& /*State*/);

// 用于 Dreaming、对话、或者任何非数值的返回
DECLARE_DELEGATE_TwoParams(FOnLLMResponseRaw, bool, const FString&);
/**
 * 
 */
UCLASS()
class AINPC_API ULLMCommunicator : public UObject
{
	GENERATED_BODY()

public:
	void Init(const FString& InApiKey, const FString& InUrl = TEXT("https://api.deepseek.com/chat/completions"));
	void SendRequest(const FString& UserInput, FOnLLMResponse OnComplete);

	// 它不会尝试解析 FMentalState，而是直接把 LLM 说的话原封不动给你
	void SendRequestRaw(const FString& Prompt, FOnLLMResponseRaw OnComplete);
	
private:
	void OnResponseReceived(FHttpRequestPtr Request, FHttpResponsePtr Response, bool bWasSuccessful);

	// === 【新增】通用内部回调 ===
	void OnResponseReceivedRaw(FHttpRequestPtr Request, FHttpResponsePtr Response, bool bWasSuccessful);
	
	FString ApiKey;
	FString ApiUrl;
	
	// ✅ 修复并发冲突：使用 TMap 存储多个请求的回调
	// Key: HTTP请求指针, Value: 对应的回调函数
	TMap<FHttpRequestPtr, FOnLLMResponse> PendingCallbacks;
	TMap<FHttpRequestPtr, FOnLLMResponseRaw> PendingRawCallbacks;

	// 语义映射器 / Sentiment Mapper
	// 将 LLM 输出的标签转换为数值
	UPROPERTY()
	USentimentMapper* SentimentMapper;
};